# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/study/competition_fuse_pzfs/competition.srcs/sources_1/ip/vga_rom/vga_rom.xci
# IP: The module: 'vga_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/study/competition_fuse_pzfs/competition.srcs/sources_1/ip/vga_rom/vga_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/study/competition_fuse_pzfs/competition.srcs/sources_1/ip/vga_rom/vga_rom.xci
# IP: The module: 'vga_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/study/competition_fuse_pzfs/competition.srcs/sources_1/ip/vga_rom/vga_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
