# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/competition_synthesize/competition.cache/wt [current_project]
set_property parent.project_path D:/competition_synthesize/competition.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/competition_synthesize/competition.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/../coe/pictureone.coe
add_files c:/Users/21311/Desktop/CrazyBird.coe
add_files D:/../coe/picturetwo.coe
read_verilog -library xil_defaultlib {
  D:/competition_synthesize/competition.srcs/sources_1/new/Erosion.v
  D:/study/fpga/gesture_recognition/ov7725_EGO1/Chapter_12/Digital_camera/files/HDL_source/IP_Catalog/XUP_IICctrl_1.0/sources_1/imports/src/I2C_Controller.v
  D:/study/fpga/gesture_recognition/ov7725_EGO1/Chapter_12/Digital_camera/files/HDL_source/IP_Catalog/XUP_IICctrl_1.0/sources_1/imports/src/IICctrl.v
  D:/competition_synthesize/competition.srcs/sources_1/new/IICctrl_0.v
  D:/competition_synthesize/competition.srcs/sources_1/new/Img_Processor.v
  D:/competition_synthesize/competition.srcs/sources_1/new/RGB_YCBCR.v
  D:/competition_synthesize/competition.srcs/sources_1/new/Shift_RAM_3X3.v
  D:/competition_synthesize/competition.srcs/sources_1/new/Shift_RAM_3x3_1bit.v
  D:/competition_synthesize/competition.srcs/sources_1/new/Sobel_Edge_Detect.v
  D:/study/fpga/gesture_recognition/ov7725_EGO1/Chapter_12/Digital_camera/files/HDL_source/IP_Catalog/XUP_cam_ov7670_ov7725_1.0/cam_ov7670_ov7725.v
  D:/competition_synthesize/competition.srcs/sources_1/new/cam_ov7670_ov7725_0.v
  D:/competition_synthesize/competition.srcs/sources_1/new/count_study.v
  D:/competition_synthesize/competition.srcs/sources_1/new/dilation.v
  D:/competition_synthesize/competition.srcs/sources_1/new/dynamic_gest_judge.v
  D:/competition_synthesize/competition.srcs/sources_1/new/fuse.v
  D:/competition_synthesize/competition.srcs/sources_1/new/gesture_judge.v
  D:/competition_synthesize/competition.srcs/sources_1/new/hu_judge.v
  D:/competition_synthesize/competition.srcs/sources_1/new/hu_martix.v
  D:/competition_synthesize/competition.srcs/sources_1/new/ov7725.v
  D:/study/fpga/gesture_recognition/ov7725_EGO1/Chapter_12/Digital_camera/files/HDL_source/IP_Catalog/XUP_ov7725_regData_1.0/ov7725_regData.v
  D:/competition_synthesize/competition.srcs/sources_1/new/ov7725_regData_0.v
  D:/competition_synthesize/competition.srcs/sources_1/new/picture_show.v
}
read_ip -quiet D:/competition_synthesize/competition.srcs/sources_1/ip/div_gen_32bit/div_gen_32bit.xci
set_property used_in_implementation false [get_files -all d:/competition_synthesize/competition.srcs/sources_1/ip/div_gen_32bit/div_gen_32bit_ooc.xdc]

read_ip -quiet D:/competition_synthesize/competition.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
set_property used_in_implementation false [get_files -all d:/competition_synthesize/competition.srcs/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc]

read_ip -quiet D:/competition_synthesize/competition.srcs/sources_1/ip/Shift_RAM_3x3_bit/Shift_RAM_3x3_bit.xci
set_property used_in_implementation false [get_files -all d:/competition_synthesize/competition.srcs/sources_1/ip/Shift_RAM_3x3_bit/Shift_RAM_3x3_bit_ooc.xdc]

read_ip -quiet D:/competition_synthesize/competition.srcs/sources_1/ip/Shift_RAM_3X3_8bit/Shift_RAM_3X3_8bit.xci
set_property used_in_implementation false [get_files -all d:/competition_synthesize/competition.srcs/sources_1/ip/Shift_RAM_3X3_8bit/Shift_RAM_3X3_8bit_ooc.xdc]

read_ip -quiet D:/competition_synthesize/competition.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/competition_synthesize/competition.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/competition_synthesize/competition.srcs/constrs_1/new/competition.xdc
set_property used_in_implementation false [get_files D:/competition_synthesize/competition.srcs/constrs_1/new/competition.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top picture_show -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef picture_show.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file picture_show_utilization_synth.rpt -pb picture_show_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
